<section class="panel">
    <div class="panel-heading"><span class="section-number">03</span><div><h2>Bukti pengeluaran dana</h2><p>Nomor dan hari pembayaran diisi tangan setelah dicetak. Lengkapi nominal, keperluan, dan penerima pembayaran.</p></div></div>
    <div class="field"><label for="voucher-number">Nomor bukti pada hasil cetak</label><input id="voucher-number" value="/REV.SMK" readonly><small>Bagian angka sebelum /REV.SMK dikosongkan untuk ditulis tangan setelah dicetak.</small></div>
    <div class="field"><label for="received-from">Sudah terima dari <span class="auto-field-badge">Otomatis</span></label><input id="received-from" value="{{ config('voucher.fixed_fields.received_from') }}" readonly></div>
    <div class="field"><label for="amount">Nominal (Rp)</label><input type="number" id="amount" name="amount" value="{{ old('amount', $document->amount) }}" min="0" max="999999999999" step="1" placeholder="Contoh: 6150328"><small>Masukkan angka tanpa titik/koma. Terbilang dibuat otomatis pada hasil cetak.</small></div>
    <div class="field"><label for="purpose">Untuk keperluan</label><textarea id="purpose" name="purpose" rows="3" maxlength="1000" placeholder="Contoh: Perjalanan dinas kegiatan Bimtek bantuan pemerintah program revitalisasi SMK">{{ old('purpose', $document->purpose) }}</textarea></div>
    <div class="fields-row"><div class="field"><label for="payment-month">Bulan dan tahun lunas dibayar <span class="auto-field-badge">Otomatis</span></label><input id="payment-month" value="{{ ($document->receipt_date ?? now())->translatedFormat('F Y') }}" readonly><small>Bulan dan tahun mengikuti tanggal nota. Bagian hari dikosongkan pada hasil cetak untuk ditulis tangan.</small></div><div class="field"><label for="payment-place">Tempat pembayaran <span class="auto-field-badge">Otomatis</span></label><input id="payment-place" value="{{ config('voucher.fixed_fields.payment_place') }}" readonly></div></div>
    <div class="payment-signers">
        <h3>Setuju dibayar <span class="auto-field-badge">Otomatis</span></h3>
        <div class="automatic-signer"><strong>{{ config('voucher.fixed_fields.approver_title') }}</strong><p>{{ config('voucher.fixed_fields.approver_name') }}</p><span>NIP {{ config('voucher.fixed_fields.approver_nip') }}</span></div>
        <h3>Bendahara <span class="auto-field-badge">Otomatis</span></h3>
        <div class="automatic-signer"><strong>{{ config('voucher.fixed_fields.treasurer_name') }}</strong><span>NIP {{ config('voucher.fixed_fields.treasurer_nip') }}</span></div>
        <h3>Penerima pembayaran</h3><div class="fields-row"><div class="field"><label for="recipient-name">Nama penerima pembayaran</label><input id="recipient-name" name="recipient_name" value="{{ old('recipient_name', $document->recipient_name) }}" maxlength="150" placeholder="Masukkan nama penerima pembayaran"></div><div class="field"><label for="recipient-nip">NIP penerima pembayaran</label><input id="recipient-nip" name="recipient_nip" value="{{ old('recipient_nip', $document->recipient_nip) }}" maxlength="32" placeholder="Opsional"><small>Kosongkan jika penerima tidak memiliki NIP.</small></div></div>
    </div>
</section>
